version: "3"

dotenv: ['.env']

tasks:
  build:
    cmds:
      - if [ "$ENV" != "local" ]; then go build -o ./bin/app ./cmd/app/main.go; fi
  run:
    deps: [compose, build]
    env:
      CONFIG_PATH: ./.env
    cmds:
      - if [ "$ENV" == "local" ]; then air; else ./bin/app; fi
  test:
    cmds:
      - go test -v -race ./...
  lint:
    cmds:
      - golangci-lint run ./...
  compose:
    cmds:
      - docker compose up -d
  push:
    deps: [lint, test]
    cmds:
      - git add .
      - git commit -m "{{.CLI_ARGS}}"
      - git push -u origin master