version: "3"

tasks:
  build:
    cmds:
      - go build -o ./bin/app ./cmd/app/main.go
  run:
    deps: [build]
    env:
      CONFIG_PATH: ./.env
    cmds:
      - ./bin/app
  test:
    cmds:
      - go test ./...
  lint:
    cmds:
      - golangci-lint run ./...
  compose:
    cmds:
      - docker compose up -d
  push:
    deps: [lint, test]
    cmds:
      - git add .
      - git commit -m "{{.CLI_ARGS}}"
      - git push -u origin master